### ISSUE TITLE
Create OpenVPN install script

### ISSUE THREAD

**Issue by hellais** [TheTorProject/ooni-probe#430]
We should create the installation script for OpenVPN so that we can run the test documented here: https://github.com/TheTorProject/ooni-spec/pull/45
and implemented here: https://github.com/TheTorProject/ooni-probe/pull/411

cc @mrphs

**Comment by anadahz** [comment]
OpenVPN doesn't require any complex installation.
In most systems it's just an installation of the openvpn package.
Having an install on the test documentation page (rst) is enough.
@juga0 @srvetus

**Comment by anadahz** [comment]
This has been already implemented [here](https://github.com/TheTorProject/ooni-probe/blob/master/scripts/openvpn_install.sh) and [here](https://github.com/TheTorProject/ooni-probe/blob/master/docs/source/tests/openvpn.rst#how-to-install-openvpn).
