### ISSUE TITLE
Incompatibility with Twisted==15.5.0

### ISSUE THREAD

**Issue by andresazp** [TheTorProject/ooni-probe#439]
On my installs, the current master seems to be incompatible with Twisted==15.5.0.

It does work with Twisted==15.4.0

I'm not sure if this comes as a consequence merge #437. As I was using 1.3.2 with those fixes before twisted 15.5 was on pip

**Comment by bassosimone** [comment]
Yes, I've also seen this in travis-ci when I merged #437. Around the time I merged #437 I had a chat with @hellais in which he confirmed that the issue we're talking about is a txtorcon issue that must be fixed upstream (they were pulling some bits of Twisted that now have been removed from Twisted).

**Comment by hellais** [comment]
When this PR https://github.com/meejah/txtorcon/pull/147 get's merged in txtorcon and a new release is done, we should be all set.
