### ISSUE TITLE
Use JSON instead of YAML when submitting reports to backend collectors

### ISSUE THREAD

**Issue by hellais** [TheTorProject/ooni-probe#444]
Currently we use YAML when we submit reports to backend collectors. This incurs in an unreasonable amount of overhead due to the fact that we then need to re-convert the reports to JSON to perform spark based transformations on top of the data.

ooni-probes should instead use JSON as a data format when submitting to collectors and write JSON files directly to avoid the having the CPU intensive re-transformation.

**Comment by bassosimone** [comment]
@hellais I guess this has now been implemented, can we close the issue?

**Comment by hellais** [comment]
Yup!
