### ISSUE TITLE
Ubuntu dependencies error (14.04)

### ISSUE THREAD

**Issue by glamrock** [TheTorProject/ooni-probe#460]
So I'm consistently getting these errors when trying to install from either the PPA or via aptitude (as @anadahz suggested in #434):

```
 ooniprobe : Depends: python-characteristic which is a virtual package.
             Depends: python-cryptography which is a virtual package.
```

For python-cryptography, the package seems to have a very long list of chained dependencies that won't automagically install.  python-cryptography *will* install successfully via pip, but will not satisfy ooniprobe's dependency.  Chasing this down a bit, installing that requires `python-cffi <1.1.0`, which is not available via apt for 14.04. Installing `python-cffi 1.50` manually requires `python-cffi-backend`

Ultimately, ooniprobe is just not compatible with Ubuntu 14.04.  I chased this down for numerous dependencies, many of which required versions only available in 15.10 or 16.04.  Additionally, `libssl-dev` will endlessly ask for libssl1.0.0, when it is already installed.  

```


python-cryptography : Depends: python-cffi (>= 1.1.0) but 0.8.2-0ubuntu1 is installed
                      Depends: python-enum34 but it is not installed
                      Depends: python-idna but it is not installable
                      Depends: python-ipaddress but it is not installable
                      Depends: python-pyasn1 but it is not installed
                      Depends: libssl1.0.0 (>= 1.0.2~beta3) but 1.0.1f-1ubuntu2.16 is installed

Dependency is not satisfiable: python-cffi (>= 1.1.0)

The following packages have unmet dependencies:
 ooniprobe : Depends: python-characteristic but it is not installable
             Depends: python-cryptography but it is not installable
W: Ignoring Provides line with DepCompareOp for package python-cffi-backend-api-max
W: Ignoring Provides line with DepCompareOp for package python-cffi-backend-api-min
W: You may want to run apt-get update to correct these problems
E: Unable to correct problems, you have held broken packages.

Dependency is not satisfiable: python-idna
Dependency is not satisfiable: python-ipaddress

Dependency is not satisfiable: libssl1.0.0 (>= 1.0.2~beta3)
Dependency is not satisfiable: libssl1.0.0 (= 1.0.2d-0ubuntu1.3)

```

Again, most of these I was able to install by downloading the deb and installing with gdebi. But that really shouldn't be required.  I didn't get a chance to chase down the deps for `python-characteristic` before giving up and deciding to use Vagrant (because holy shit I've got thirty boxes to set up and this setup process would be a total nightmare).

**Comment by hellais** [comment]
Thanks for reporting this, this does sound quite sub-optimal. We will look into a possible way to fix the ppa. In the meantime another possible workaround would be to instead install ooniprobe directly from pip (and hence getting all the required dependencies from there).

**Comment by irl** [comment]
This does indeed sound suboptimal. I'm planning to look at the ooniprobe packaging next week, along with other Internet measurement software, and hopefully will be able to fix this in the PPA then. I'm planning to set up a series of VMs to allow me to perform better testing of the PPA packages as mostly I've been relying on people submitting bugs where they don't work on versions I haven't been able to test on.

**Comment by glamrock** [comment]
@hellais Ah yes, double facepalm to me for not realizing it was installable via pip. =)  Thanks for looking into fixing the PPA.

**Comment by hellais** [comment]
@irl have you figured out what is the source of this issue? Can we consider this closed?

**Comment by hellais** [comment]
Is this still relevant? cc @irl

**Comment by irl** [comment]
Was previously waiting to upload new .debs to deb.torproject.org but there's really no reason I can't build new debs and continue to push them to the PPA.

For the PPA, the last upload will have a NEWS file (displayed to people upgrading) that will point them to update their apt sources so this should be an easyish transition.

On my todo list today: new debs for the PPA based on the latest release for all suites.

**Comment by irl** [comment]
@glamrock @the-solipsist The Ubuntu PPA has now been updated to the latest upstream version. I have run a test installation in an Ubuntu Trusty minimal chroot and all dependencies appear to be present. Backports for Tor and txtorcon are now also present in the PPA.

I will close this issue now, but please re-open if you're still finding problems.
