### ISSUE TITLE
Update OONI documentation

### ISSUE THREAD

**Issue by anadahz** [TheTorProject/ooni-probe#466]
OONI documentation should be updated in an automated way to reflect new changes and additions.

https://ooni.torproject.org/docs/
https://ooni.readthedocs.org/en/latest/index.html

**Comment by hellais** [comment]
What exactly is meant by "automated way"?

As part of the website update process there is a script that you run and the site is updated. It requires credentials and keys to be able to push to torproject.org.

Given the frequency with which documentation is updated I don't think it's a big deal to have to run a script every time the docs are updated.

Would like to learn more about what you have in mind exactly though.

**Comment by anadahz** [comment]
This has been already implemented [here](https://github.com/TheTorProject/ooni-web/blob/b7525f2751b134502689578c5f2040fc6fd3ce20/Makefile).
