### ISSUE TITLE
ooniresources --update-geoip fails over tor

### ISSUE THREAD

**Issue by willscott** [TheTorProject/ooni-probe#478]
when attempting to set up ooniprobe from a network with censorship, it is reasonable to torify the download ```torify ooniresources --update-inputs --update-geoip```.
However, the geoip files are downloaded directly from maxmind, which returns 403 forbidden when accessed via tor.
Would be great to download these from a location accessible via tor.

**Comment by hellais** [comment]
Perhaps we could add the inputs and the geoip data files as binaries to the github release.

**Comment by hellais** [comment]
In the to be released 1.4.0 version of ooniprobe instead of downloading the resources from various sources we download them all from a `tar.gz` that is included as part of the github release.

This should make it possible to run ooniresources also via tor.

**Comment by bassosimone** [comment]
Could this issue be closed? It seems to me that the functionality was implemented, right?

**Comment by hellais** [comment]
truth.
