### ISSUE TITLE
support unix-socket tor control ports

### ISSUE THREAD

**Issue by willscott** [TheTorProject/ooni-probe#479]
The tor control port is currently hard-coded as a tcp socket
https://github.com/TheTorProject/ooni-probe/blob/master/ooni/settings.py#L212

in a debian system tor for instance, it would be preferable to connect to the unix control socket. this cannot currently be specified.

**Comment by meejah** [comment]
In the `TorConfig` instance you pass in, you can specify your own `ControlPort` config and that will be respected by `txtorcon`. So, e.g.:

```
config = TorConfig()
config.ControlPort = 'unix:/var/log/tor/control`
# ... etc
```

**Comment by hellais** [comment]
This is now implemented thanks to @ioef!
