### ISSUE TITLE
randomize order of url test list

### ISSUE THREAD

**Issue by willscott** [TheTorProject/ooni-probe#480]
after running oonideckgen, the global list of tests the probe begins running is always in alphabetical order.
On some connections, triggering censorship will cause degradation not just for the censored connection, but also temporally on subsequent connections.  Without randomizing the order of testing, some domains may appear to be censored when really it's the previous tests that regularly cause those tests to be run when the network is in a bad state.

**Comment by hellais** [comment]
Implementation notes:

* It should be a configurable option that goes inside of the global configuration (ooniprobe.conf)

* Probably we want to implement this by loading the whole input list in memory and using a randomisation algorithms such as the Fisher–Yates shuffle

**Comment by hellais** [comment]
Given the new deck format it's somewhat easier to implement this. I think a good place to hook the randomisation of the testing lists could be:

https://github.com/TheTorProject/ooni-probe/blob/master/ooni/deck/store.py#L54

IRC this should be run every day, but maybe some adjustment can be made to have it run every time a test needs to be run (if we want to make it even stronger).
