### ISSUE TITLE
When we encounter a HTTPS url also test the HTTP version

### ISSUE THREAD

**Issue by hellais** [TheTorProject/ooni-probe#487]
In https://github.com/citizenlab/test-lists/issues/40 there are plans to make the URLs for all sites supporting HTTPS `https://`.

This would mean that we would no longer be detecting when censorship is happening based on HTTP request line path inspection for such sites.

I propose that we implement in ooniprobe support for testing also the `HTTP` version of websites that are `HTTPS`.

**Comment by bassosimone** [comment]
Implemented in #770
