### ISSUE TITLE
-g option should explain that IP is not redacted from the reports

### ISSUE THREAD

**Issue by anadahz** [TheTorProject/ooni-probe#498]
This info needs to be added:
- Update document to mention that doesn't apply when the -g command line option is activated.
- Update OONI related documentation
- Add info to the -g command line option when ooni-probe help is invoked

Relevant [discussion](https://github.com/TheTorProject/ooni-spec/pull/57#discussion_r62433263).

**Comment by hellais** [comment]
This has been implemented.
