### ISSUE TITLE
oonireport must use the default bouncer/collector if none specified

### ISSUE THREAD

**Issue by anadahz** [TheTorProject/ooni-probe#515]
`$ oonireport -f ~/.ooni/ooniprobe.conf upload`

```
[!] Failed to run oonireport
Attempting to upload report-http_requests-XXXXX.yamloo
^CTraceback (most recent call last):
  File "/home/user/ooni-probe/ooni-env/lib/python2.7/site-packages/ooniprobe-1.5.0-py2.7.egg/EGG-INFO/scripts/oonireport", line 32, in start
    d = defer.maybeDeferred(cli.run)
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/ooniprobe-1.5.0-py2.7.egg/ooni/report/cli.py", line 71, in run
    options['bouncer'])
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/home/user/ooni-probe/ooni-env/local/lib/python2.7/site-packages/ooniprobe-1.5.0-py2.7.egg/ooni/report/tool.py", line 54, in upload
    "No collector or bouncer specified"
exceptions.Exception: No collector or bouncer specified and collector not in report log.
```

**Comment by hellais** [comment]
Can you show me the content of `~/.ooni/reporting.yml`. I changed the behaviour of oonireport with dealing with collectors on purpose, because previously it would attempt to upload to the canonical bouncer/collector also reports that had been generated by specifying a custom collector or with reporting disabled.

I don't think we want to have people upload to us reports that were produced when running ooniprobe with `-n` unless they explicitly specify a collector/bouncer address.

**Comment by anadahz** [comment]
There is quite some content in `reporting.yml` but not relevant to these reports.
That is actually how I run oonireport to upload reports, since I often move files around which `reporting.yml` cannot keep track:
`for f in *yamloo ; do  oonireport -f ~/.ooni/ooniprobe.conf upload $f; done`

**Comment by bassosimone** [comment]
@hellais is it possible, and does it make sense, to tag reports generated with either custom collector or reporting disabled such that oonireport could act on them correctly?

**Comment by hellais** [comment]
Hum, that is an interesting idea. Actually we could add a key to the report header that specifies what is the address of the collector or if it has been disabled and if so doesn't submit it.

This sounds like a good way around this issue.

**Comment by hellais** [comment]
For the moment I implemented a temporary fix for this that should have a slightly better behaviour. Basically if we find the target report_file inside of the reporting.yaml file and collector is None we will not upload it. If however we don't find it inside of reporting.yaml then we will upload it by getting the collector address from the canonical bouncer.

@anadahz if this looks like a good fix for you, then I can merge it and tag another release to include this fix.

**Comment by anadahz** [comment]
When on a very slow link or a limited bandwidth network point I tend to not report to a collector as this minimizes bandwidth utilization and decreases total time needed for the tests.

@hellais I guess it makes sense to add an option to override this [case](https://github.com/TheTorProject/ooni-probe/blob/de75b701f0b5d25e4362cdaacb7c20815a41928d/ooni/report/tool.py#L52-56).
