### ISSUE TITLE
Debian ooniprobe package ooniprobe.log should be logrotated in a different way

### ISSUE THREAD

**Issue by anadahz** [TheTorProject/ooni-probe#518]
In Debian package version of ooniprobe log rotation is being handled by [logrotate](https://anonscm.debian.org/cgit/collab-maint/ooniprobe.git/tree/debian/ooniprobe.logrotate).
This is not really ideal as it 'll produce weird (binary) ooniprobe log files.

A hacky way of resolving this in [lepidopter](https://github.com/TheTorProject/lepidopter/pull/31).

This will be solved by  #502 .

**Comment by hellais** [comment]
I believe this can now be closed?

**Comment by anadahz** [comment]
Log rotation is already implemented in ooniprobe, closing this ticket.
