### ISSUE TITLE
silently ignores '--pcapfile' flag

### ISSUE THREAD

**Issue by mrphs** [TheTorProject/ooni-probe#521]
When I run

    ooniprobe --pcapfile=output.pcap -n third_party/openvpn --openvpn-config=config.ovpn --url=site.com

`ooniprobe` silenty ignores `--pcapfile=` option and proceeds.

**Comment by hellais** [comment]
In order to collect `pcaps` you also need to enable PCAP collection in `~/.ooni/ooniprobe.conf` by setting ```
privacy:
    # Should we collect a full packet capture on the client?
    includepcap: false
```

**Comment by mrphs** [comment]
hm then if it's not enabled, it should return an error with instructions on how to enable it.

**Comment by hellais** [comment]
Yes indeed.

**Comment by mrphs** [comment]
Thinking a bit more about this... when I call `--pcapfile=` I clearly am asking for this to happen. So maybe a better fix is to ignore `includepcap` state when `--pcapfile=` is called.
