### ISSUE TITLE
Support not running ooniresources on setup.py

### ISSUE THREAD

**Issue by hellais** [TheTorProject/ooni-probe#535]
It would be better to support skipping the call to ooniresources in the setup.py with an optional flag (ex. `--no-resources`).

This use case became apparent when when updating the formula for homebrew in https://github.com/Homebrew/homebrew-core/pull/1869

**Comment by RohanVB** [comment]
id like to be assigned this issue please.

**Comment by hellais** [comment]
Hi @RohanVB I invited you to join the ooni-read team and then I will be able to assign you to the issue.
Thanks!

**Comment by RohanVB** [comment]
thanks. I received your invitation and I joined. @hellais

**Comment by hellais** [comment]
Here you go 😄

**Comment by RohanVB** [comment]
Requesting unassignment. I'm unable to fix this issue.

**Comment by hellais** [comment]
This is no longer relevant since we don't need ooniresources anymore.
