### ISSUE TITLE
Extract amqp

### ISSUE THREAD

**Issue by willscott** [TheTorProject/ooni-probe#560]
Per https://github.com/TheTorProject/ooni-probe/pull/549#issuecomment-226899622
We should consider having options only relevant to ```ooniprobequeue``` not be included in the main ```ooni-probe``` binary.
That said, where is ```ooniprobequeue```?

**Comment by hellais** [comment]
Actually ooniprobequeue is now merged into ooniprobe itself and the code path for it is enabled conditionally on the using of the `--queue` option.

**Comment by hellais** [comment]
Can we consider this no longer valid?

If not please re-open it.
