### ISSUE TITLE
Make a system daemon for ooniprobe

### ISSUE THREAD

**Issue by hellais** [TheTorProject/ooni-probe#576]
There should be a system daemon that is responsible for exposing the ooniprobe web UI and starting the periodic tasks (such as running the default deck daily, updating the inputs, etc.).

This system daemon will be called `ooniprobe-agent`.

**Comment by anadahz** [comment]
An systemd service for ooniprobe has being implemented in: https://github.com/TheTorProject/lepidopter/pull/74/commits/e07502c0bba742f61452c7d2891b6d824b18f95a

In lepidopter I'm placing the unit file in path `etc/systemd/system/` (ie. for units installed by the system admin) but the path `/lib/systemd/system/` should be used for systemd units that are provided by installed packages.

**Comment by hellais** [comment]
This systemd service should be committed to the ooniprobe source tree as it's probably also useful for other non-raspberry pi specific packaging efforts.

**Comment by anadahz** [comment]
I have set ooniprobe's service type  to simple since the `ooniprobe-agent` process doesn't send a signal to systemd when it's ready.

For the ooniprobe package I 'll prefer if we use instead the notify service type for ooniprobe systemd unit.

**Comment by hellais** [comment]
Are you specifying the `PIDFILE` to systemd? From what I read somewhere I recall this is also what systemd uses to check if the service is up and running.

**Comment by anadahz** [comment]
> Are you specifying the PIDFILE to systemd?
https://github.com/TheTorProject/lepidopter/pull/74/commits/e07502c0bba742f61452c7d2891b6d824b18f95a#diff-ae7fbb13f7e6d5e6bc9106ac5633e229R7

Re:  documentation of unit types https://www.freedesktop.org/software/systemd/man/systemd.service.html#Type=

**Comment by hellais** [comment]
I think `forking` would perhaps then be a more appropriate type. In our particular deployment scenario it's not so relevant, but it's probably best to wait for the parent process to quit before "setting up followup services".

**Comment by anadahz** [comment]
From systemd.service manual page:
> Behavior of notify is similar to simple; however, it is expected that the
> daemon sends a notification message via sd_notify(3) or an equivalent call
> when it has finished starting up. systemd will proceed with starting follow-up
> units after this notification message has been sent.

Does ooniprobe-agent notify the system when it starts/stops?

**Comment by hellais** [comment]
@anadahz I was suggesting you use `forking` not `notify`.

**Comment by hellais** [comment]
This is implemented.
