### ISSUE TITLE
[2.0.0 release] Bug report - ooniprobe-agent should bind only to localhost

### ISSUE THREAD

**Issue by anadahz** [TheTorProject/ooni-probe#589]
Currently ooniprobe-agent binds in all available interfaces (`0.0.0.0:8842`). 
Instead ooniprobe-agent's port should be exposed only to localhost interface.

**Comment by hellais** [comment]
I think this should be a configurable option in the configuration file though, since we want in lepidopter based probes to expose the web interface on the local network (not just localhost).

**Comment by hellais** [comment]
Implemented fix for this. Closing.
