### ISSUE TITLE
[2.0.0 release] Bug report - ooniproge-agent reports incorrect state

### ISSUE THREAD

**Issue by anadahz** [TheTorProject/ooni-probe#597]
When ooniprobe-agent is being started by systemd the output of `ooniprobe-agent status` returns `ooniprobe-agent is NOT running` when ooniprobe-agent is running:
```
root       398  5.9  7.6 115716 72948 ?        Sl   05:52   3:59 /usr/bin/python /usr/local/bin/ooniprobe-agent start
```
`lepidopter@lepidopter:~$ ooniprobe-agent start`
```
Starting ooniprobe agent.
To view the GUI go to http://127.0.0.1:8842
An error has occurred: 'Couldn't listen on any:8842: [Errno 98] Address already in use.'
Please look at log file for more information.
```
We should ensure that:
- [x] ooniprobe-agent status output should always be consistent
- [x] ooniprobe-agent should not be allowed to start (or even try start) by multiple users in the system until we enable support for this.

**Comment by hellais** [comment]
Are you running `ooniprobe-agent status` as root? If not it will not find it to be running, because the pid files are generated per user and the status is checked per user.

I will think a bit about how we can make the behaviour work also for non-root users.

**Comment by anadahz** [comment]
As per the bug report https://github.com/TheTorProject/ooni-probe/issues/597#issue-174451311 `ooniprobe-agent status` is running an a non root user (user lepidopter).

Since there is no support for multiple instances of ooniprobe-agent  and as we don't want to be running `ooniprobe-agent` multiple times in a system it makes sense to remove the status option and deploy some checks that will not allow ooniprobe-agent to start if another instance is already running system wide.

We can find the status of the ooniprobe-agent from systemd:
`lepidopter@lepidopter:~$ systemctl status ooniprobe`
```
● ooniprobe.service - ooniprobe.service, network interference detection tool
   Loaded: loaded (/etc/systemd/system/ooniprobe.service; enabled)
   Active: active (running) since Thu 1970-01-01 00:00:10 UTC; 46 years 8 months ago
 Main PID: 398 (ooniprobe-agent)
   CGroup: /system.slice/ooniprobe.service
           ├─398 /usr/bin/python /usr/local/bin/ooniprobe-agent start
           ├─407 /usr/sbin/tor -f /non-existant --ignore-missing-torrc Bridge obfs4 X.X.X.X..
           └─415 /usr/bin/obfs4proxy
```

**Comment by hellais** [comment]
This is now resolved.
