### ISSUE TITLE
web_connectivity: do not follow redirects on the local host

### ISSUE THREAD

**Issue by bassosimone** [TheTorProject/ooni-probe#605]
Currently the web_connectivity test will follow redirects also when the redirect is towards private IP addresses.

This is problematic for 2 reasons:
- It can lead to false positives because obviously if a site is hosted in private ip space it will not match to the site hosted in private IP space on the control.
- It can lead to potential privacy leaks if the user is hosting something sensitive on local ip space.

**Comment by darkk** [comment]
That's also true for *connected* LAN for the same reasons.

I'm unsure if it's true for all RFC1918 nets as the blockpage MAY be served using "private" server.

**Comment by darkk** [comment]
That's also true for *connected* LAN for the same reasons.

I'm unsure if it's true for all RFC1918 nets as the blockpage MAY be served using "private" server.

**Comment by hellais** [comment]
This is now merged.
