### ISSUE TITLE
Progress bar or expected time remaining

### ISSUE THREAD

**Issue by willscott** [TheTorProject/ooni-probe#613]
Especially when running a deck interactively, it would be very helpful to be able to see progress with finer granularity than that a test is running. Especially for web-connectivity, where the test is run sequentially per-url, this can be as simple as providing a line of output as each new input is processed to indicate e.g. that this is test 100/500.

**Comment by hellais** [comment]
I think this is a very good suggestion, thought it's not as simple to implement as you would think.

Currently we don't go through the whole list of URLs so we don't actually know when we start a test what is the total input count.

I think doing this is probably not too hard and I would probably do as part of this also some randomisation of the order in which URLs are tested (as per: https://github.com/TheTorProject/ooni-probe/issues/480)

**Comment by bassosimone** [comment]
fyi: measurement-kit emits the progress during the test. This is currently done through the logging subsystem which receives a log message formatted as JSON and can be [processed similarly to what we do in netprobe-ios](https://github.com/measurement-kit/netprobe-ios/blob/master/NetProbe/Model/NetworkMeasurement.mm#L156) to inform the user of progress.

**Comment by hellais** [comment]
This is done.
