### ISSUE TITLE
Investigate occasional locking of the web UI

### ISSUE THREAD

**Issue by hellais** [TheTorProject/ooni-probe#619]
In testing the web UI it seems like sometimes the web UI becomes irresponsive for 2-3 seconds (HTTP requests stay pending for many seconds).

This is most probably due to blocking code that is interleaved with non blocking code.

We should look into places where there is code that is blocking either on IO or CPU and refactor it to use non blocking IO or spawn off threads.

Noticed in https://github.com/TheTorProject/ooni-probe/issues/612

**Comment by darkk** [comment]
Have you found any root cause so far? I can try to get a reproducible test-case.

**Comment by hellais** [comment]
@darkk #621 resolved one of the issues I was having. There may be more issues like this lurking around so I haven't closed it, but I was able to reproduce the problem before and after #621 (manually though, without a proper unittest as it requires browser interaction).

**Comment by darkk** [comment]
I've checked pcap's & devtools — it's not the some sort of blocking code (confirmed by strace) or CPU-intensive code (confirmed by cpuacct.stat) that is causing 7…20 seconds lags, it's my Firefox-49.0 being slow crunching megabytes of javascript code in single process.

I can't reproduce the issue event **without** #621 fix using either Firefox instance with clear **profile** (Private browsing does not help) or chromium 53.0.2785.143.

It's quite interesting that ooni-probe UI makes my "day-to-day" FF instance to hog CPU and spend 50% of time running GC despite having 2G of free RAM, but that's probably is not worth debugging unless someone else complains. :-)

**Comment by hellais** [comment]
This is fixed.
