### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by Shuailong** [TheTorProject/ooni-probe#641]
There is a 404 error for resource https://libdnet.googlecode.com/files/libdnet-1.12.tgz when installing ooniprobe using homebrew in macOS

**Comment by hellais** [comment]
It seems like this issue with the libdnet formula was fixed in https://github.com/Homebrew/homebrew-core/commit/2db28631bf8acaba76b6f41e8a92613c8846bf05.

Can you try running:

```
brew update
```

and then seeing if the installation works then?

**Comment by Shuailong** [comment]
Solved!! Thank you very much!!
