### ISSUE TITLE
Error while running "oonideckgen" in Ubuntu terminal

### ISSUE THREAD

**Issue by LeafylsHere** [TheTorProject/ooni-probe#656]
Here's what I get:

> Resources for running ooniprobe are not up to date.
> Will update them now.
> Downloading https://github.com/TheTorProject/ooni-probe/releases/download/v1.6.0/ooni-resources.tar.gz to /home/john/.ooni
> Failed to download resources!
> [!] Failed to run oonideckgen
> Traceback (most recent call last):
> File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 434, in errback
>     self._startRunCallbacks(fail)
> File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
>     self._runCallbacks()
> File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 587, in _runCallbacks
>     current.result = callback(current.result, _args, *_kw)
> File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1241, in gotResult
>     _inlineCallbacks(r, g, deferred)
> --- <exception caught here> ---
> File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1183, in _inlineCallbacks
>     result = result.throwExceptionIntoGenerator(g)
> File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
>     return g.throw(self.type, self.value, self.tb)
> File "/usr/lib/python2.7/dist-packages/ooni/deckgen/cli.py", line 148, in run
>     yield download_resources()
> File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1185, in _inlineCallbacks
>     result = g.send(result)
> File "/usr/lib/python2.7/dist-packages/ooni/resources/update.py", line 54, in download_resources
>     raise exc
> exceptions.OSError: [Errno 2] No such file or directory

**Comment by hellais** [comment]
Hi @LeafylsHere, thanks for running ooniprobe!

It seems like you are running an out of date version that is no longer supported (in later versions oonideckgen is no longer needed).

Newer packages for debian and ubuntu are also on their way. In the meantime if you want you can try installing a later version of ooniprobe with pip.

This issue also was already filed as part of: https://github.com/TheTorProject/ooni-probe/issues/648
