### ISSUE TITLE
vanilla_tor should not use cached data from system-wide tor

### ISSUE THREAD

**Issue by darkk** [TheTorProject/ooni-probe#666]
`vanilla_tor` uses cached data from system-wide tor, so measurement may be skewed.

Imagine [blocked authorities](https://ooni.torproject.org/post/egypt-network-interference/#attempts-to-block-tor) — vanilla_tor check will pass, but real bootstrap of fresh tor client will be painfully slow.

**Comment by hellais** [comment]
I am looking now at the test and it actually seems like we are not using the cached data from system wide tor (or at least attempt to not do it).

See: https://github.com/TheTorProject/ooni-probe/blob/master/ooni/nettests/blocking/vanilla_tor.py#L46
https://github.com/TheTorProject/ooni-probe/blob/master/ooni/nettests/blocking/vanilla_tor.py#L62

Have I tried to find some evidence of this in the data, but don't seem to find it.

Are you able to stably reproduce this?

**Comment by hellais** [comment]
I believe this actually does not happen in the vanilla_tor test. If you believe that is not the case please re-open the ticket and provide instructions on how to reproduce.
