### ISSUE TITLE
Investigate possible misalignment of local report_id vs backend report_id

### ISSUE THREAD

**Issue by hellais** [TheTorProject/ooni-probe#673]
In comparing the report_id stored on the disk of a probe and the one submitted to a collector it seems like they are misaligned.

We should look into if that is the case or not.

**Comment by hellais** [comment]
I tried to reproduce this with the current version of ooniprobe and could not reproduce.

@anadahz do you know what version of ooniprobe you had on your pis in brazil?

**Comment by anadahz** [comment]
Since it was running the 4h update the ooniprobe at that time was `2.0.1`.
The report file name: `20161111T000118Z-BR-AS7738-meek_fronted_requests_test`

The report file in that Pi has been long deleted from the ooniprobe quota scheduler.

**Comment by hellais** [comment]
Ok I am going to close this in the meantime as I cannot reproduce.
