### ISSUE TITLE
[Debian testing] ooniprobe fails to initialize when /etc/ooniprobe.conf exists -- Permission denied: '/var/lib/ooni/ooniprobe.conf'

### ISSUE THREAD

**Issue by anadahz** [TheTorProject/ooni-probe#680]
When ` /etc/ooniprobe.conf` contains any config options ooniprobe fails to initialize 
due to permissions errors. The ooniprobe service and the WUI run without issues.

```
ooniprobe:
  Installed: 2.0.1-1
  Candidate: 2.0.1-1
  Version table:
 *** 2.0.1-1 0
        500 http://ftp.us.debian.org/debian/ testing/contrib amd64 Packages
        100 /var/lib/dpkg/status
```
---------------------------------------------
Steps to reproduce:

Install ooniprobe Debian package from testing/contrib.

Stop ooniprobe service:
```
systemctl stop ooniprobe
```
Add some config options in `/etc/ooniprobe.conf`:
```
printf '%s\n    %s\n    %s\n' 'advanced:' 'webui_port: 8080' 'webui_address:
"0.0.0.0"' >> /var/lib/ooni/ooniprobe.conf
```
Go through ooniprobe's setup wizard.
In last step (4) of the setup wizard the message `Failed to configure ooniprobe` is 
being displayed  and ooniprobe fails to initialize.

Relevant log:
```
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 149, in maybeDeferred
            result = f(*args, **kw)
          File "/usr/lib/python2.7/dist-packages/klein/app.py", line 108, in execute_endpoint
            return endpoint_f(self._instance, *args, **kwargs)
          File "/usr/lib/python2.7/dist-packages/klein/app.py", line 193, in _f
            return _call(instance, f, request, *a, **kw)
          File "/usr/lib/python2.7/dist-packages/klein/app.py", line 35, in _call
            return f(instance, *args, **kwargs)
          File "/usr/lib/python2.7/dist-packages/ooni/ui/web/server.py", line 68, in wrapper
            return f(instance, request, *a, **kw)
          File "/usr/lib/python2.7/dist-packages/ooni/ui/web/server.py", line 86, in wrapper
            return f(instance, request, *a, **kw)
          File "/usr/lib/python2.7/dist-packages/ooni/ui/web/server.py", line 321, in api_initialize
            config.create_config_file(**options)
          File "/usr/lib/python2.7/dist-packages/ooni/settings.py", line 448, in create_config_file
            with open(self.user_config_file_path, 'w') as out_file:
        exceptions.IOError: [Errno 13] Permission denied: '/var/lib/ooni/ooniprobe.conf'
```

**Comment by hellais** [comment]
You are adding configuration options inside of `/var/lib/ooni/ooniprobe.conf` not `/etc/ooniprobe.conf`.

The configuration options inside of `/var/lib/ooni/ooniprobe.conf` are to be managed by ooniprobe itself and the ooniprobe process needs to have access to this file.

If you need to change configuration options for ooniprobe you should either:

1) Write them to `/etc/ooniprobe.conf`

2) Edit `/var/lib/ooni/ooniprobe.conf` **after** you have completed the first start wizard

**Comment by anadahz** [comment]
@hellais you are right confused with PATH.
This issue report is invalid, closing.
