### ISSUE TITLE
Update ooniprobe package in deb.torproject.org dists trusty and xenial

### ISSUE THREAD

**Issue by anadahz** [TheTorProject/ooni-probe#681]
The dists [trusty](https://deb.torproject.org/torproject.org/dists/trusty/main/binary-amd64/Packages) and [xenial](https://deb.torproject.org/torproject.org/dists/xenial/main/binary-amd64/Packages) in `deb.torproject.org` are using an older ooniprobe version (1.6.1-1).

The dists trusty xenial should include the latest ooniprobe version as in the
[yaketty](https://deb.torproject.org/torproject.org/dists/yakkety/main/binary-amd64/Packages) dist.

Affects: #649, https://github.com/TheTorProject/ooni-web/pull/94

cc: @irl

**Comment by hellais** [comment]
There is now 2.0.1 inside of deb.torproject.org.
