### ISSUE TITLE
Brew install fails on MacOS

### ISSUE THREAD

**Issue by johnflan** [TheTorProject/ooni-probe#714]
### Description

Brew fails to install ooniprobe

### Steps to Reproduce

1. Execute `brew install libdnet`
2. Fails with error
```
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "libdnet"
Download failed: https://libdnet.googlecode.com/files/libdnet-1.12.tgz
```

**Comment by hellais** [comment]
This is likely happening due to your homebrew being out of date (and the older libdnet formula referencing a now dead URL).

Can you try running:

```bash
brew update && brew install libdnet
```

Then try installing ooniprobe with:

```bash
brew install ooniprobe
```

**Comment by hellais** [comment]
xref: https://github.com/TheTorProject/ooni-probe/issues/641

**Comment by johnflan** [comment]
You were completely right, sorry for troubling you.

**Comment by hellais** [comment]
Great!

Thanks for running ooniprobe! :)

**Comment by johnflan** [comment]
No worries, I seen it mentioned in a CCC talk. Cheers for your efforts
