### ISSUE TITLE
web connectivity: CNAME passed along causing control request failure

### ISSUE THREAD

**Issue by bassosimone** [TheTorProject/ooni-probe#727]
### Description

When poking around with #723, I noticed that for input `http://www.kernel.org/` the `CNAME` is also passed to the backend, causing it to fail.

### Steps to Reproduce

1. ooniprobe -v web_connectivity -u http://www.kernel.org/

<details><summary>Backtrace of the error</summary>

Only relevant logs. For more complete (irrelevant) logs, see TheTorProject/ooni-sysadmin#83.

```
$ ooniprobe -v web_connectivity -u http://www.kernel.org/
[...]
Starting test for http://www.kernel.org/
* doing DNS query for www.kernel.org
A Lookup successful
[...]
Adding [Query('www.kernel.org', 1, 1)] to report)
* connecting to pub.all.kernel.org:80
* connecting to 198.145.20.140:80
* connecting to 199.204.44.194:80
* connecting to 149.20.4.69:80
* doing HTTP(s) request http://www.kernel.org/
[...]
* performing control request with backend
Querying backend https://a.web-connectivity.th.ooni.io:4442/ with {'tcp_connect': ['pub.all.kernel.org:80', '198.145.20.140:80', '199.204.44.194:80', '149.20.4.69:80'], 'http_request': 'http://www.kernel.org/'}
Got this backend error message {u'error': u'Invalid tcp_connect URL'}
[!] Failed to perform control lookup: unknown_failure 
```
</details>

**Expected behavior:** either the backend should be able to deal with a CNAME or the client should not pass along the CNAME. I believe the former is more correct, since my understanding is that the CNAME information is used to perform DNS related checks on the client side.

**Actual behavior:** The CNAME is passed along and the control request fails because of that.

### Further information

**How did you install ooniprobe**

Did you install ooniprobe via the **debian package**, **homebrew** or **pip**? pip

**What operating system are you running and what version is it?** macOS 10.12.3

<details><summary>Output of `ooniprobe -v --info`</summary>

```
Paths
-----
inputs directory: $HOME/src/github.com/TheTorProject/ooni-probe/venv/var/lib/ooni/inputs
scheduler directory: $HOME/src/github.com/TheTorProject/ooni-probe/venv/var/lib/ooni/scheduler
resources directory: $HOME/src/github.com/TheTorProject/ooni-probe/venv/var/lib/ooni/resources
decks available directory: $HOME/src/github.com/TheTorProject/ooni-probe/venv/share/ooni/decks-available
decks enabled directory: $HOME/src/github.com/TheTorProject/ooni-probe/venv/var/lib/ooni/decks-enabled
measurements directory: $HOME/src/github.com/TheTorProject/ooni-probe/venv/var/lib/ooni/measurements
running path: $HOME/src/github.com/TheTorProject/ooni-probe/venv/var/lib/ooni
config files: $HOME/src/github.com/TheTorProject/ooni-probe/venv/var/lib/ooni/ooniprobe.conf,/etc/ooniprobe.conf
ooni home: $HOME/.ooni
var_lib path: $HOME/src/github.com/TheTorProject/ooni-probe/venv/var/lib/ooni
etc path: $HOME/src/github.com/TheTorProject/ooni-probe/venv/etc
usr_share path: $HOME/src/github.com/TheTorProject/ooni-probe/venv/share/ooni
nettest directory: $HOME/src/github.com/TheTorProject/ooni-probe/venv/lib/python2.7/site-packages/ooniprobe-2.2.0rc0-py2.7.egg/ooni/nettests
web ui directory: $HOME/src/github.com/TheTorProject/ooni-probe/venv/lib/python2.7/site-packages/ooniprobe-2.2.0rc0-py2.7.egg/ooni/ui/web/client

```
</details>

<details><summary>Output of `ooniprobe --version`</summary>

```
ooniprobe version: 2.2.0.rc0
```
</details>

**Comment by hellais** [comment]
So I think that this issue is actually inside of ooniprobe itself, since the value is being passed inside of the tcp_connect field, from what I can tell.

The purpose of the tcp_connect field is, "hey see if you can connect to these IPs on these ports". Adding an extra DNS resolution there would be wrong.

I suggest that to fix this though we do the following:

* [ ] Add support for handling hostnames in the tcp_connect field in ooni-backend
* [ ] Do not transmit this as part of ooniprobe web_connectivity test

**Comment by bassosimone** [comment]
@hellais: yeah, I think that's the right way to completely address this issue
