### ISSUE TITLE
Problem of installation of the new Tor version

### ISSUE THREAD

**Issue by BitWaspBitWasp** [TheTorProject/ooni-probe#737]
### Description

When I install Tor from debian repository(apt-get install tor) - it works - no problem

but in this case I have old Tor version 0.2.5.12

so I tried to install newer version

Added to /etc/apt/sources.list 
deb http://deb.torproject.org/torproject.org jessie main
deb-src http://deb.torproject.org/torproject.org jessie main

apt-get install tor deb.torproject.org-keyring

Installation was successful

But when I tried to add a domain - I have errors:
[warn] Couldn't open "/var/tor/hosts/xxxxxxxxxxxxxxxx.onion/hostname.tmp" (/var/tor/hosts/xxxxxxxxxxxxxxxx.onion/hostname) for writing: Read-only file system
[warn] Could not write onion address to hostname file.
[warn] Error loading rendezvous service keys

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

<details><summary>Backtrace of the error</summary>

```
[paste output here]
```
</details>

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Further information

**How did you install ooniprobe**

Did you install ooniprobe via the **debian package**, **homebrew** or **pip**?

**What operating system are you running and what version is it?**

<details><summary>Output of `ooniprobe -v --info`</summary>

```
[paste output here]
```
</details>

<details><summary>Output of `ooniprobe --version`</summary>

```
[paste output here]
```
</details>

**Comment by hellais** [comment]
@BitWaspBitWasp you should file issues pertaining to tor on the Tor issue tracker: https://trac.torproject.org/projects/tor/newticket.

That said I believe the issue you are having has to do with the fact that you have configured your tor client to expose a Tor Hidden Service and you specified as `HiddenServiceDir` a path that is mounted on a read-only filesystem. Try changing the path to `HiddenServiceDir` to something that is not on a read-only filesystem or re mount the partition in read write.

**Comment by BitWaspBitWasp** [comment]
HiddenServiceDir  is a folder(not a disc) and have the same permissions for old and new version.
With old version it works, with all the same settings new version doesn't work.
Are there new requirements for Tor's new version ?

**Comment by BitWaspBitWasp** [comment]
I only updated Tor software.
All config files and HiddenServiceDir etc. are old(the same)
