### ISSUE TITLE
how to run ooni probe faster from terminal

### ISSUE THREAD

**Issue by PravalikaRao** [TheTorProject/ooni-probe#754]
When I gave OONI probe an input file with 30 links to check whether they are censored or not and blocked or not in particular country, it took 30 minutes to give the output. But I want to give an input file (.csv) with more than 5k-50k URLs at a time. How can I make this process faster and reduce the time? 

**Steps to Reproduce**
1.I have given a folder of 30 URLs to run to ooniprobe through web connectivity
2. $ooniprobe blocking/web_connectivity --file sample1.csv
3. It took 30 minutes to run 30 URLs
**Expected behavior:**
To run OONI probe faster than expected.
**Actual behavior**
It is taking too long time to run only 30 URLs but I want to run more than 50k URLs at a time.

**Comment by hellais** [comment]
Do a lot of the URLs fail because of a timeout?

Something you can do to try to improve the performance (especially if many URLs timeout) is to tune your `ooniprobe.conf` file to have a higher concurrency.

The values specifically:

```
    # After how many seconds we should give up on a particular measurement
    measurement_timeout: 120
    # How many measurements to perform concurrently
    measurement_concurrency: 4
    # After how may seconds we should give up reporting
    reporting_timeout: 360
    # How many reports to perform concurrently
    reporting_concurrency: 7
```

If you have a fast network, something like `measurement_concurrency: 10` and `reporting_concurrency: 16` should be fine.

**Comment by PravalikaRao** [comment]
Thank you @hellais, For helping me out. 
I have changed the configuration in the `ooniprobe.conf` file:

        `$nano /home/labuser/Enthought/Canopy_64bit/User/var/lib/ooni/ooniprobe.conf`

Under section `#advanced` I changed `measurement_concurrency: 10` and `reporting_concurrency: 16`

               `#measurement_timeout: 120
                # After how many retries we should give up on a measurement
                #measurement_retries: 2
                # How many measurements to perform concurrently
                #measurement_concurrency: 10
                # After how may seconds we should give up reporting
                #reporting_timeout: 360
                # After how many retries to give up on reporting
                #reporting_retries: 5
                # How many reports to perform concurrently
                 #reporting_concurrency: 16`

I have given a file with `30 URLs` in nettests and it took `60 sec` to give the results.

@hellais Now you can close the issue.

**Comment by hellais** [comment]
You commented out the line right? (remove the leading `#`). 60 seconds still seems like a lot of time, you can maybe make it better by tweaking a bit those parameters to best suite your needs.

Anyways glad it did the trick!
