### ISSUE TITLE
add privacy respect apps to the list of instant messaging apps

### ISSUE THREAD

**Issue by oonimooni** [TheTorProject/ooni-probe#765]
whatsapp and facebookmessenger and telegram ? i really wonder why would anyone care for these apps to c them even working , i would be really happy to c all of them blocked by all countries.

whatsapp owned by facebook , its closed source and privacy issue

facebookmessenger = holy kingdom of censorship , ofc closed source

Telegram = not fully open source ,  revealed some of its users to the authorities so also privacy issue

why not u encourage the users to use some privacy respect apps by adding them to the list of test, or just replace these privacy sucking apps with them. for e.g:- 

[Signal](https://whispersystems.org/) 

[WIre](https://wire.com/en/)

 [Ring](https://ring.cx/)

**Comment by hellais** [comment]
Hi @oonimooni thanks for reaching out to us!

We chose to implement tests for those three apps in the first iteration as those are the ones that are most widely used in the world (you can find some details on the rational here: https://github.com/TheTorProject/ooni-probe/issues/602, there is also a link to user stats for every app including some of the ones you mentioned above)>

That said ooniprobe is free and open source software so if you would like to see tests for one or more of the apps you mentioned above, you should totally implement a test for them!

**Comment by bassosimone** [comment]
Because they are censored and relevant to many people. So it makes sense to measure them. (We don't encourage people to use them, it's the other way round: people use them, so we measure.)

Of course, more tests for more apps are welcome. If you could write a test checking for the blocking of any app you mention, we will be very grateful and happily review it and provide advice.

**Comment by oonimooni** [comment]
@hellais @bassosimone 

i didnt get it , these apps already censored by default/design so u r measuring it and then telling the user oh there is censoring evidences from/on them ? 

its like the user is riding a car with explosives inside it , and its already mentioned on the car that it carry explosives and all what we r doing is just admitting what has been already been written on the car to the user.

so proving they r censored or not it will not be a matter of effect to anything. because these apps never claimed that they r anonymity/privacy providers , they r just usability providers. 

but when we prove that there r censoring evidences on apps providing privacy/anonymity care for the user, then it will be useful for the user and even for the app developers to circumvent censoring methods.

regarding my help for programming = if im a programmer it would be great to help u guys, sadly im not programmer im just reporter. 

thanks

**Comment by hellais** [comment]
@oonimooni 

1. Github is not a forum or a mailing list. If you have things you would like to discuss you should join our mailing list and post a message about these things there: https://lists.torproject.org/cgi-bin/mailman/listinfo/ooni-dev or https://lists.torproject.org/cgi-bin/mailman/listinfo/ooni-talk

2. ooniprobe doesn't measure platform censorship (where the owner of the platform decides to remove or censor the flow of certain messages), but only censorship at the network level

3. whatsapp communication is actually end-to-end encrypted using the same protocol that is used by signal. For futher reading see: https://whispersystems.org/blog/there-is-no-whatsapp-backdoor/ and https://www.whatsapp.com/security/WhatsApp-Security-Whitepaper.pdf

I am going to close this as not-a-bug.
