### ISSUE TITLE
Allow user-set urls on ooni mobile apps 

### ISSUE THREAD

**Issue by Tafiti** [TheTorProject/ooni-probe#776]
### Description

Enabling ooni mobile users to input specific urls or at the least test their country's test list. 

### Further information
Currently, ooni mobile tests random urls and it seems there is no user control of the 'web connectivity' test list. 
It would be a significant utility to introduce such a functionality where users can easily paste a url on the app (like in the WebUI or CLI) and get instant report about it. 
At the very least though, it should be possible to test using the specific country citizenlab url list where the test is being run from.

**Comment by hellais** [comment]
Issue moved to [TheTorProject/ooniprobe-ios #120](https://github.com/TheTorProject/ooniprobe-ios/issues/120) via [**ZenHub**](https://www.zenhub.com/)
