### ISSUE TITLE
So screw windows users who are censored ?

### ISSUE THREAD

**Issue by pushqrdx** [TheTorProject/ooni-probe#782]
I am just curious, Tor is completely blocked in my country now, no access to Tor website, or relays (bootstraping hangs on 10%) i thought i could run the analysis on my machine but only linux and mac are supported ? i mean why!

**Comment by hellais** [comment]
Hi Ahmed, thanks for your interest in running OONI Probe!
We are working on developing a new version of OONI Probe with the primary target platform being windows. We are aiming to have an alpha version of it out by mid 2018.

The current version of OONI Probe has a series of dependencies that make it hard to port to a non posix system and so the new version (3.0) is being rewritten from the ground up with Windows support in mind.

**Comment by pushqrdx** [comment]
alright that's amazing thanks a lot for your reply. I am just saying though You have Egypt colored blue on your website.. it's no more. Tor is blocked everywhere here now along with a bunch of other freedom of speech websites and VPN services.

**Comment by kevinfengcu** [comment]
If you have Windows 10 see if you can get Windows Subsystem for Linux. That way you can enjoy most Linux stuff while getting rid of virtual machine hassle.
